# Generated by Django 3.0.6 on 2020-06-22 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_auto_20200622_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='precio_c_iva',
            field=models.CharField(default=2, max_length=250),
        ),
    ]
