# Generated by Django 3.0.6 on 2020-06-22 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_productos_precio_c_iva'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribuidores',
            name='direccion',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
