# Generated by Django 3.0.6 on 2020-06-23 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0007_auto_20200623_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='precio',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='productos',
            name='precio_c_iva',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
