# Generated by Django 3.0.6 on 2020-06-23 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0009_auto_20200623_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='iva',
        ),
        migrations.AlterField(
            model_name='productos',
            name='precio_c_iva',
            field=models.DecimalField(blank=True, decimal_places=250, max_digits=250),
        ),
    ]
