# Generated by Django 3.0.6 on 2020-06-24 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0012_auto_20200624_0039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='precio_c_iva',
        ),
        migrations.AddField(
            model_name='productos',
            name='preciociva',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='distribuidor',
            field=models.ManyToManyField(to='producto.distribuidores'),
        ),
    ]
