# Generated by Django 3.0.6 on 2020-06-24 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0013_auto_20200624_0101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='preciociva',
        ),
        migrations.AddField(
            model_name='productos',
            name='precio_c_iva',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
