# Generated by Django 3.0.6 on 2020-06-24 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0014_auto_20200624_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='precio_c_iva',
            field=models.FloatField(null=True),
        ),
    ]
