# Generated by Django 3.0.6 on 2020-06-24 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0015_auto_20200624_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='precio_c_iva',
            field=models.CharField(blank=True, default=1, max_length=250),
            preserve_default=False,
        ),
    ]
