# Generated by Django 3.0.6 on 2020-06-24 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0016_auto_20200624_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='iva',
            field=models.DecimalField(decimal_places=10, default=1.21, max_digits=14),
        ),
        migrations.AlterField(
            model_name='productos',
            name='precio',
            field=models.DecimalField(decimal_places=10, max_digits=14),
        ),
    ]
