# Generated by Django 3.0.6 on 2020-06-24 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0018_auto_20200624_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='precio',
            field=models.DecimalField(decimal_places=10, max_digits=14),
        ),
    ]
