# Generated by Django 3.0.6 on 2020-06-24 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0020_auto_20200624_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='precio_venta',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='productos',
            name='remarcado',
            field=models.DecimalField(decimal_places=10, default=1, max_digits=14),
            preserve_default=False,
        ),
    ]
