# Generated by Django 3.0.6 on 2020-06-24 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0021_auto_20200624_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='remarcado',
            field=models.DecimalField(decimal_places=10, help_text='colocar 1, antes del valor remarcado', max_digits=14),
        ),
    ]
