# Generated by Django 3.0.6 on 2020-06-24 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0023_auto_20200624_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='iva',
            field=models.DecimalField(decimal_places=4, default=1.21, max_digits=7),
        ),
        migrations.AlterField(
            model_name='productos',
            name='remarcado',
            field=models.DecimalField(decimal_places=4, help_text='colocar 1, antes del valor remarcado', max_digits=7),
        ),
    ]
